[package]
name = "egui-chinese-font-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
egui-chinese-font = { path = ".." }
eframe = "0.27"
egui = "0.27"

[[bin]]
name = "basic"
path = "basic.rs"
